### ISSUE TITLE
[Mark of Pride] Damage increase doesn't work

### ISSUE THREAD

**Issue by drsgdev** [DistractionCrab/Charm-Crab#10]
I think root cause is this function not being called so stack count is always 0:
https://github.com/DistractionCrab/Charm-Crab/blob/2155221ff5d5723a0273ad2890c7b7aa22be5113/Charms/Charms/MarkOfPride.cs#L40-L43

**Comment by DistractionCrab** [comment]
Yeah, it's not being called where it should be. Probably got forgotten when I refactored slash hits. I'll get to fixing this here soon.

Thanks for letting me know!

**Comment by drsgdev** [comment]
> Yeah, it's not being called where it should be. Probably got forgotten when I refactored slash hits. I'll get to fixing this here soon.
> 
> Thanks for letting me know!

Created a [PR](https://github.com/DistractionCrab/Charm-Crab/pull/11)

**Comment by DistractionCrab** [comment]
See commit ec7639b for the general fix I intended. PR #11 I've commented on the reasons why I made my change as opposed to the suggested ones. Feel free to disagree or yell at me if there are still issues.

I will leave this open until I get a chance to put up a new release for scarab (which will follow Issue #9 being resolved or deemed to problematic).

**Comment by drsgdev** [comment]
> See commit [ec7639b](https://github.com/DistractionCrab/Charm-Crab/commit/ec7639b8aefa14b845b607ea4500a00827f56720) for the general fix I intended. PR #11 I've commented on the reasons why I made my change as opposed to the suggested ones. Feel free to disagree or yell at me if there are still issues.
> 
> I will leave this open until I get a chance to put up a new release for scarab (which will follow Issue #9 being resolved or deemed to problematic).

Alright. Waiting for the release then. I'll try to compile the fix myself for now.

**Comment by drsgdev** [comment]
Should be `stacks += 1`
https://github.com/DistractionCrab/Charm-Crab/blob/ec7639b8aefa14b845b607ea4500a00827f56720/Charms/Charms/MarkOfPride.cs#L41

**Comment by DistractionCrab** [comment]
Fixed. Surprised the compiler let me get away with that one. Thanks!

**Comment by drsgdev** [comment]
> Fixed. Surprised the compiler let me get away with that one. Thanks!

=+ is a viable operator

**Comment by DistractionCrab** [comment]
Fixed in dcd9c5a
