### ISSUE TITLE
[Mark of Pride] Some enemies take constant damage

### ISSUE THREAD

**Issue by drsgdev** [DistractionCrab/Charm-Crab#12]
Damage doesn't increase with consecutive hits on some enemies (and even bosses) like:
[Glimback](https://hollowknight.fandom.com/wiki/Glimback)
[Crystal Guardian](https://hollowknight.fandom.com/wiki/Crystal_Guardian)
[Stalking Devout](https://hollowknight.fandom.com/wiki/Stalking_Devout)
(not a complete list)

They also seem to take constant damage from spells (even with the Shaman Stone equipped). It seems like Mark of Pride stacks just doesn't apply from hits for these enemies.

**Comment by DistractionCrab** [comment]
Is this happening when you're tinking on their protected parts, or does this also happen when you deal damage to them? You only get the bonus if you hit something that can take damage (includes the situation that if you hit a blocker, but not a vulnerable spot).

**Comment by drsgdev** [comment]
> Is this happening when you're tinking on their protected parts, or does this also happen when you deal damage to them? You only get the bonus if you hit something that can take damage (includes the situation that if you hit a blocker, but not a vulnerable spot).
> 
> As for shaman stone issue, I'll look into it. Could be some custom logic for these enemies.

Ofc I mean when actually dealing damage to them. It just doesn't increase (I have damage numbers mod installed).

**Comment by DistractionCrab** [comment]
No need to be defensive, mate. I don't know what you're doing, so I'm asking the standard questions to get the information I need.

Regardless I'll look into it tonight.

**Comment by drsgdev** [comment]
> No need to be defensive, mate. I don't know what you're doing, so I'm asking the standard questions to get the information I need.
> 
> Regardless I'll look into it tonight.

I didn't mean to be defensive, it just sounds like it. No offence. Just trying to help :)

**Comment by DistractionCrab** [comment]
Understood, my mistake. Appreciate the help!

**Comment by DistractionCrab** [comment]
Alright, so I did some testing, and the reason why the crystal enemies don't give stacks is the fact that they are considered "invincible," i.e. their "IsInvincible" variable is set to true, even though they can take damage (even from the front). So I'm going to do some testing and see if removing this check is back (considering I have many other checks to remove redundant events from causing issues, it may be safe, but who knows!).  Going to do some testing. 

As for spells,  I cannot recreate any the effect. Fireball (without Shaman stone)  does like 100 damage and with Shaman stone, it does 400 damage. So it's working as intended AFAIK. Are you running any other gameplay mods? If so, add a list of them to this post, and I'll check out some interactions and see if I need to change how I'm handling something.

**Comment by drsgdev** [comment]
> Alright, so I did some testing, and the reason why the crystal enemies don't give stacks is the fact that they are considered "invincible," i.e. their "IsInvincible" variable is set to true, even though they can take damage (even from the front). So I'm going to do some testing and see if removing this check is back (considering I have many other checks to remove redundant events from causing issues, it may be safe, but who knows!). Going to do some testing.
> 
> As for spells, I cannot recreate any the effect. Fireball (without Shaman stone) does like 100 damage and with Shaman stone, it does 400 damage. So it's working as intended AFAIK. Are you running any other gameplay mods? If so, add a list of them to this post, and I'll check out some interactions and see if I need to change how I'm handling something.

What about the Stalking Devout? I also might've misjudged spell dmg by the numbers. Might actually work as intended.

**Comment by DistractionCrab** [comment]
I just checked the Stalking Devouts, and they're properly applying Pride stacks.

If you run into any issues with spells feel free to add them here again; There's always the chance something weird happens randomly. Especially with some of the hacky things needed to be done.

**Comment by DistractionCrab** [comment]
Now fixed in dcd9c5a
