### ISSUE TITLE
Acid doesn't work in Royal Waterways

### ISSUE THREAD

**Issue by drsgdev** [DistractionCrab/Charm-Crab#13]
For some reason I was able to swim in acid in Royal Waterways. I had Compass, Swarm, Dash\Sprint-master, Sharp Shadow, Mark of Pride equipped.
Acid in other locations work as expected.

**Comment by DistractionCrab** [comment]
I can't recreate this issue. The acid is affecting me normally. What other mods are you using? Could be an interaction that I don't know about and I may need to play nicer with others.

**Comment by drsgdev** [comment]
![image](https://github.com/DistractionCrab/Charm-Crab/assets/37770887/41f17749-6a31-43bb-a090-e3643dca79bc)

**Comment by DistractionCrab** [comment]
Alright, I'll do some messing around with this. I do some SFM manipulations that could be doing this randomly under specific conditions, so all I can do is keep trying to recreate it.

This will probably be a longer issue that may not make it into 1.0.6, but if that's the case it's fine. Restarting the game should fix any invincibility issues.
