### ISSUE TITLE
Void Tendrils Doesn't Work

### ISSUE THREAD

**Issue by Lobsterlucnhbox** [DistractionCrab/Charm-Crab#18]
Self explanatory but basically the void tendrils charm does not change abyss shriek

**Comment by DistractionCrab** [comment]
Went and tested. Seems to just be in the main story and not in the Boss Rush mode. I'll start looking into this today.

**Comment by DistractionCrab** [comment]
This should be resolved in fe0d90e 

I'll try to get around to pushing an update to Scarab here soon. In the meantime, tendrils should be working on the old patch, but only on the first load into a file. So if they're not working, reload the game entirely and load into a file. AFAIK I don't know any other situations that cause this issue, so if it pops up again feel free to open another issue or comment on this issue again.

**Comment by DistractionCrab** [comment]
Release published in v1.0.8

https://github.com/DistractionCrab/Charm-Crab/releases/tag/v1.0.8
