### ISSUE TITLE
personal experience using the mod so far moment

### ISSUE THREAD

**Issue by LukianDagbo** [DistractionCrab/Charm-Crab#2]
In my gaming experience, it was very frustrating for me to kill the elder baldur since it was necessary to load soul and only get soul from the enemies that it generates, in addition to the fact that life and damage have different scales, I needed to be practically a long time to be able to kill them, also in different areas due to the differences in damage scale in certain situations, the enemies generated accumulated in excess and resulted in situations that needed greater upgrades to be able to overcome areas that could be done at certain times.
Excluding those specific problems, I really like all the changes that the mod has, in addition to the rebalances and the improvements and nerfs that it implements since in the vanilla game you are practically immortal since you constantly generate souls, instead in the mod you must rationalize the soul and choose between use it offensively or defensively, I hope there are more patches to be able to continue improving this game experience that until now seems very successful, especially if you have already played a lot of hk.
again thank you very much for bringing this mod I think anyone who has played the game will really like these improvements and nerfs.
In addition, I have not yet fully completed the game with the mod, so I cannot give my full experience of the mod, if not how far I have come, I think the last thing I played I did not explore deepnest, I did not get the double jump, monarch and void heart and none of the 3 dreamers.

**Comment by DistractionCrab** [comment]
Elder Baldurs (at least the second one going towards Greenpath) I'm honestly just thinking of removing. Baldurs given their locations are not well designed for the pacing I have in mind). I may try to explicitly hit their health, but I'll have to find out some bits of information so I can target them specifically, so those should be changed at some point. Believe me, I hated fighting the Baldurs during my test run also.

For generated enemies, I haven't personally run into an issue with them *yet* but it depends on which ones you are fighting. Did a specific one give you issues? If so I can take a look at it, because some enemies spawning extra ones are a pain to code due to how they work. Especially Fluke Marm (which is much more difficult at an early junction).

**Comment by LukianDagbo** [comment]
Just to comment that in certain situations the enemies that spawn enemies end up revealing more than what you are used to in the vanilla experience, the change doesn't bother me anyway, and I like that it increases the difficulty when facing enemies with those characteristics back on topic of baldur if there is a possibility of eliminating it there is a possibility of generating an infinite soul totem to be able to knock it down.
Again, thank you very much for the mod and stay tuned for the feedback.
I look forward to many future releases, so far I haven't found anything to dislike and I like this new experience that all the changes implemented in the mod bring

**Comment by LukianDagbo** [comment]
Just to comment that in certain situations the enemies that spawn enemies end up revealing more than what you are used to in the vanilla experience, the change doesn't bother me anyway, and I like that it increases the difficulty when facing enemies with those characteristics back on topic of baldur if there is a possibility of eliminating it there is a possibility of generating an infinite soul totem to be able to knock it down.
Again, thank you very much for the mod and stay tuned for the feedback.
I look forward to many future releases, so far I haven't found anything to dislike and I like this new experience that all the changes implemented in the mod bring
