### ISSUE TITLE
Possible error in the shadow with Geo

### ISSUE THREAD

**Issue by LukianDagbo** [DistractionCrab/Charm-Crab#3]
I am not sure that the error is due when it happened to me, I had fragile greed and Spell twister when killing in the shade I multiply the geo that it possessed it was approximately 15K and I have 35k it is not clear to me that the error is due to the error I will try to die of Different ways to identify the possible cause, at the moment I will continue playing and testing everything I find if I find any specific error I will comment so far and the Steady Body was solved and the Baldun tried since I am testing the version in a run in a run that I had already killed I think I still did not look for the charm baldur so I will surely check that this is.

**Comment by DistractionCrab** [comment]
This is an interesting one; Not one I expected to pop up, but I think I see why it happens.

I want to make sure of something: When you died and came back to your shade did you re-equip Fragile Greed? (i.e. you died, with it unequipped, and equipped it on the way back to your shade). If this is the case, then it shouldn't be a big issue to fix.

**Comment by LukianDagbo** [comment]
Dead without Greed Charm and when I went to recover my geo. I went with the equipped charm greed

**Comment by DistractionCrab** [comment]
Alright, excellent. I should have it fixed now; I just needed to be sure there wasn't a possible other avenue for it.  Thanks!

**Comment by LukianDagbo** [comment]
Thank you very much for bringing this great mod. I'm having a lot of fun with him!
Any abnormality that you find or situations that do not seem part of the mod try to notifying you.
I thank you again for the mod!
