### ISSUE TITLE
Fragile greed negative geo

### ISSUE THREAD

**Issue by ErioirE** [DistractionCrab/Charm-Crab#7]
I had fragile greed equipped and somehow ended up with negative geo after making a few purchases. Not exactly sure how it happened.

**Comment by DistractionCrab** [comment]
Thanks for letting me know, I made a change to make sure it doesn't happen and I'll look into testing this and pushing out an update here soon.

**Comment by DistractionCrab** [comment]
Alright, an update should be live here soon for this fixing this issue in v1.0.3.

Will close this in a bit.
